version: '3'
services:
  bot:
    build: .
    container_name: tg-bot-custom
    restart: always
    ports:
      - "${HOST_PORT}:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
